---
- hosts: apt-hosts
  become: yes
  become_user: root
  pre_tasks:
    - name: Get ansible_user home directory
      shell: 'getent passwd "{{ansible_ssh_user}}" | cut -d: -f6'
      register: ansible_home_result

    - name: Set the fact for the other scripts to use
      set_fact: ansible_home='{{ansible_home_result.stdout}}'
  roles:
    - apt-install-packages
    - git-init-config
    - vim-init
    - nvm-init
    - ssh-init
    - ufw-init
